version: 2
jobs:
  build-gimp-2-10:
    macos:
        xcode: "10.1.0"

    steps:
        - checkout
        - run:
            name: Cleanup /usr/local
            command: sudo rm -rf /usr/local/*
        - run:
            name: Setup rust
            command: curl https://sh.rustup.rs -sSf | sh -s -- -y
        - run:
            name: Setup Python3
            command: |
              cd ~/
              curl -L 'https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg' > python-3.6.8-macosx10.9.pkg
              sudo installer -pkg python-3.6.8-macosx10.9.pkg -target /
        - run:
            name: Setup 10.12 SDK
            command: |
              cd /Library/Developer/CommandLineTools/SDKs
              sudo curl -L 'https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.12.sdk.tar.xz' | sudo tar -xzf -
              echo 'export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk' > ~/.profile
              echo 'export MACOSX_DEPLOYMENT_TARGET=10.12' >> ~/.profile
        - restore_cache:
            keys:
              - jhbuild-v12
        - run:
            name: Setup JHBuild
            command: |
              cd $HOME
              mkdir -p ~/.config && mv ~/project/jhbuildrc-gtk-osx-gimp ~/.config/jhbuildrc-custom
              curl https://gitlab.gnome.org/samm-git/gtk-osx/raw/gimp/gtk-osx-setup.sh > gtk-osx-setup.sh
              chmod +x gtk-osx-setup.sh
              echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH:$HOME/.new_local/bin"' >> ~/.profile
              echo 'export ARCHFLAGS="-arch x86_64"' >> ~/.profile
              source ~/.profile
              PIPENV_YES=1 ./gtk-osx-setup.sh
              $HOME/.new_local/bin/jhbuild bootstrap-gtk-osx-gimp
              cat ~/.profile
        - save_cache:
            paths:
              - ~/.new_local
              - ~/gtk
              - ~/.config
            key: jhbuild-v12
        - run:
            name: Setup gtk-mac-bundler
            command: |
              cd ~/Source
              git clone https://github.com/samm-git/gtk-mac-bundler -b fix-otool
              cd gtk-mac-bundler
              make install
        # we can try to make it automatically depended on the corresponding modules
        - restore_cache:
            keys:
              - gimp-2.10.22-v3a
              - webkit-v23
              - gimp-deps-v12
              - bootstrap-v23
        - run:
            name: Bootstrap
            command: source ~/.profile && jhbuild build icu55 meta-gtk-osx-freetype meta-gtk-osx-bootstrap meta-gtk-osx-core
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: bootstrap-v23
        - run:
            name: Build GIMP dependencies (without gegl/babl)
            command: |
              source ~/.profile && jhbuild build suitesparse lcms libunistring gmp libnettle libtasn1 gnutls libjpeg readline python glib-networking openjpeg  gtk-mac-integration poppler poppler-data
              source ~/.profile && jhbuild build json-glib p2tc exiv2 gexiv2 ilmbase openexr libwebp libcroco librsvg-24 json-c
              source ~/.profile && jhbuild build libmypaint mypaint-brushes libde265 nasm x265 libheif aalib shared-mime-info iso-codes libwmf libmng ghostscript
              source ~/.profile && jhbuild build pycairo pygobject pygtk gtk-mac-integration-python
        - run:
            name: Build all WebKit dependencies
            command: |
              source ~/.profile && jhbuild build enchant libpsl sqlite vala gnutls
              source ~/.profile && jhbuild buildone libsoup
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: gimp-deps-v12
        - run:
            name: Build WebKit v1
            no_output_timeout: 1h
            command: source ~/.profile && jhbuild buildone webkit
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: webkit-v23
        - run:
            name: Build and test babl/gegl
            command: source ~/.profile && jhbuild build --check babl gegl
        - run:
            name: Build GIMP
            # XXX `make check` is not working reliably under circle ci, so we are
            # not using --check flag
            command: |
              source ~/.profile
              jhbuild build gimp
        - run:
            name: Building GIMP help (en) from git
            command: source ~/.profile && ALL_LINGUAS=en jhbuild build gimp-help-git
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: gimp-2.10.22-v3a
        - run:
            name: Importing signing certificate
            command: |
              mkdir ${HOME}/codesign && cd ${HOME}/codesign
              echo "$osx_crt" | base64 -D > gnome.pfx
              curl 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer' > apple.cer
              security create-keychain -p "" signchain
              security set-keychain-settings signchain
              security unlock-keychain -u signchain
              security list-keychains  -s "${HOME}/Library/Keychains/signchain-db" "${HOME}/Library/Keychains/login.keychain-db"
              security import apple.cer -k signchain  -T /usr/bin/codesign
              security import gnome.pfx  -k signchain -P "$osx_crt_pw" -T /usr/bin/codesign
              security set-key-partition-list -S apple-tool:,apple: -k "" signchain
              rm -rf ${HOME}/codesign
        - run:
            name: Creating DMG package
            command: |
              source ~/.profile
              cd ${HOME}/project/package
              jhbuild run ./build.sh
        - run:
            name:  Notarizing DMG package
            command: |
              source ~/.profile
              cd ${HOME}/project/package
              jhbuild run ./notarize.sh
        - store_artifacts:
            path: /tmp/artifacts
            destination: builds

workflows:
  version: 2
  build-different-versions:
    jobs:
      - build-gimp-2-10
