name: PullRequest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildMac:
    name: Build macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [ Xcode_12.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: true
      - name: Investigate available XCode versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: install build environment
        run: ./build_setup.sh
      - name: Archive artifact
        uses: actions/upload-artifact@v2.2.2
        if: ${{ success() }}
        with:
          name: DLT-macOS-${{ matrix.xcode }}
          path: build/release
